[package]
name = "grpgscript-zed"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"]}
zed_extension_api = "0.7.0"
