texture = [
    { name = "grass",  id = 0, path = "../texture-packer/testdata/grass_texture.png", type = "TILE" },
    { name = "grass2", id = 1, path = "../texture-packer/testdata/grass_texture.png", type = "TILE" },
    { name = "grass3", id = 2, path = "../texture-packer/testdata/grass_texture.png", type = "TILE" },
    { name = "grass4", id = 3, path = "../texture-packer/testdata/grass_texture.png", type = "TILE" },
    { name = "grass5", id = 4, path = "../texture-packer/testdata/grass_texture.png", type = "TILE" },
    { name = "stone",  id = 5, path = "../texture-packer/testdata/stone_texture.png", type = "OBJ" },
    { name = "stone2", id = 6, path = "../texture-packer/testdata/stone_texture.png", type = "OBJ" },
    { name = "stone3", id = 7, path = "../texture-packer/testdata/stone_texture.png", type = "OBJ" },
    { name = "stone4", id = 8, path = "../texture-packer/testdata/stone_texture.png", type = "OBJ" },
]
